### ISSUE TITLE
Use reagent 0.6.0-alpha with latest re-natal

### ISSUE THREAD

**Issue by ducky427** [drapanjanas/re-natal#14]
`react-native` version `0.18.x` is dependent on `react` `0.14.x` while `reagent` `0.5.x` is dependent on `react` `0.13.x`.

These are the breaking changes for react [`0.14.0`](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#breaking-changes)

Not sure if this is really an issue but its worth highlighting.

**Comment by drapanjanas** [comment]
Good point, thanks!

**Comment by drapanjanas** [comment]
Well, it looks to me that reagent 0.6.0-alpha can not be used with react-native because it is a monolyth  and depends on "react-dom" and "react-dom/server" modules

**Comment by artemyarulin** [comment]
Have no idea about reagent, so sorry if my comment doesn't make any sense.

With om-next we also have a dependency problem that it requires `react.dom` while it's definitely doesn't work on react-native platforms. Solution requires those steps:
1. Add a dependency to om-next but use exclusion like:
`{:dependencies [[org.omcljs/om "1.0.0-alpha28" :exclusions [cljsjs/react cljsjs/react-dom]]]`
2. As now project cannot be compiled create needed files, in our case:
`echo "(ns cljsjs.react.dom)" > src/react/dom.cljs`
`echo "(ns cljsjs.react)" > src/react/react.cljs`
3. Don't use `om/dom` namespace (which actually uses cljsjs.react.dom under the hood), but rather create React Native elements

Actually for the om-next only the last one is required, first 2 needed only to make JS bundle smaller and in order to remove any possible conflicts during runtime (I guess I was having one at the beginning....)

In your case if number 3 is not possible that you can do 1-2 and then actually implement some kind of proxy to the actual react-native

**Comment by ducky427** [comment]
Looks like its gonna be challenging in reagent due to this [assert](https://github.com/reagent-project/reagent/blob/master/src/reagent/dom/server.cljs#L12).

**Comment by artemyarulin** [comment]
Not at all - we are free to implement whatever we want on our shims, for example with om-next template I'm making couple of stubs for the exactly the same reason https://github.com/artemyarulin/om-next-cross-platform-template/blob/master/resources/leiningen/new/om_next_cross_platform/react.cljs

And another important thing - maintainers of Reagent would be more than happy to make Reagent happen on React Native environment, so making PR is not a problem

**Comment by ducky427** [comment]
@artemyarulin, thats cool. Using your approach, I think it should be possible.

**Comment by drapanjanas** [comment]
Damn, it still will not work in 'prod-build' because of this [js/require line](https://github.com/reagent-project/reagent/blob/master/src/reagent/dom/server.cljs#L10) and the way packager works.
Packager scans for all occurances of require(..) in compiled js file. So, even if in our case there is no way this line is reached at runtime, it will still fail with "module not found" error.

**Comment by artemyarulin** [comment]
Hm, true. Well I guess then we can make PR OR actually make a shim for the whole namespace `reagent.dom.server`

First one is definitely a better approach

**Comment by drapanjanas** [comment]
Yep, PR would be good. There are some issues with status Open in reagent regarding React 14 and support of react native, so I will try asking maybe there are already some plans. In my opinion it would be good to have separate dependencies for reagent core and dom/dom.server. So that if you use just core no need to shim anything at all

**Comment by ducky427** [comment]
Would @holmsand's latest [commit](https://github.com/reagent-project/reagent/commit/f76bce6a2f559deaec6f392203add9521cb7c197) help?

**Comment by drapanjanas** [comment]
@ducky427 thanks for update. It does not help because packager still finds the `(js/require "react-dom")` and is not able to prepare this module. Maybe this would not happen in advanced mode in case this unused code is eliminated at all.
<img width="487" alt="screen shot 2016-02-25 at 20 03 04" src="https://cloud.githubusercontent.com/assets/1648448/13331449/cd3d034a-dbfd-11e5-9310-afd12a27fb98.png">
It works fine if I remove the [require of reagent.dom and reagent.dom.server](https://github.com/reagent-project/reagent/blob/f76bce6a2f559deaec6f392203add9521cb7c197/src/reagent/core.cljs#L11-L12) from reagent.core (and functions which delegates to them). I guess these functions are only for backward-compatibility in core.
But, actually in re-natal I can easily add new "interfaces" now.  So I could add `--interface reagent6` with simmed reagent.dom and reagent.dom.server (containing only empty functions) like @artemyarulin mentioned above. That works, I have tested it. What do you think?

**Comment by vikeri** [comment]
Any progress on this? The `--interface reagent6` would be awesome. Anything I could do to help?

**Comment by drapanjanas** [comment]
I think it almost working in branch reagent6 (with shimed namespaces), but there was some problem. I should have dumped my memory here, because now I do not remember what was not working in that branch. Need to check.

**Comment by drapanjanas** [comment]
So, reagent6 interface is avaliable in renatal@0.2.31! 
One cool thing about it is that I could remove global React variable. Now template generates local variable, and it works fine:
```
(def react-native (js/require "react-native"))
```
Feel free to test, report issues, and/or solve them :)

**Comment by artemyarulin** [comment]
@drapanjanas Am, do you mean completely or only for the Reagent? I guess Om still requires it and I assume there are plenty of libraries that expects to have React global variable?

**Comment by drapanjanas** [comment]
Oh, yes @artemyarulin, I meant only for Reagent 0.6.0-alpha. True, in case other libs needs global React variable you still need assign that. I think Regent 0.5.1 expected global var, but in 0.6.0 it falls back to require('react') which works in React Native appearently.

**Comment by artemyarulin** [comment]
Thank you for the explanation
