### ISSUE TITLE
Figwheel initialization is called twice.

### ISSUE THREAD

**Issue by bhauman** [drapanjanas/re-natal#143]
So for a generated project Figwheel initialization is called twice:

Once here:
https://github.com/drapanjanas/re-natal/blob/master/resources/cljs-rum/main_dev.cljs#L11

And again here:
https://github.com/drapanjanas/re-natal/blob/master/resources/figwheel-bridge.js#L215

Now these calls are idempotent so it's no big deal.

But it certainly could be confusing because the two different methods take their client configuration from two different places.

Requiring the `figwheel.connect.build_dev` file takes the configuration from the build config in the `project.clj`.

Calling `watch-and-reload` takes the config explicitly.

I'm mainly wanting to choose one of these ways to make it simple for everyone.

Which way of loading figwheel is the most used and most straight forward for folks?

It is also worth noting that I'm changing the way that figwheel is getting injected into a build, so now you can just `googrequire("figwheel.preload")` instead of `figwheel.connect.build_id`. But I'll submit a separate PR for that.

**Comment by jeaye** [comment]
I was just thinking about this today, but with reagent + re-frame. I think keeping this code in `figwheel-bridge.js` would be ideal. Right now, this logic is not only duplicated between `figwheel-bridge.js` and the `main` ns, it's also duplicated between Android and iOS, once the template expands the files.

Regarding passing the config through here, it also seems redundant to me, but I'm likely missing something. figwheel allows for this sort of configuration in `project.clj`, as documented here: https://github.com/bhauman/lein-figwheel#client-side-configuration-options

Thanks for bringing this up, @bhauman. :)

**Comment by jeaye** [comment]
My guess, as to why this double initialization exists (in the reagent template), is to trigger a re-render. 

https://github.com/drapanjanas/re-natal/blob/54015dbd43aaa950e7a26ecf7a94b2e4071d7ec8/resources/cljs-reagent/main_dev.cljs#L20

This `inc` of the counter on the `r/atom` will cause reagent to re-render the root element. Based on what I've seen of the `figwheel-bridge.js` version, there isn't any such code to force re-renders (and there couldn't really be, since it's specific to the rendering framework being used -- right?).

**Comment by drapanjanas** [comment]
Thanks @bhauman ! Good to know that if `watch-and-reload` is used then no need to require `figwheel.connect.build_${platform}`. I did not realize this. I think figwheel-bridge.js was more-less following what is generated in the init script for the browser (not-used.js) which requires `figwheel.connect.build_${platform}`:
```
document.write("<script>if (typeof goog != \"undefined\") { goog.require(\"figwheel.connect.build_ios\"); }</script>");
document.write('<script>goog.require("env.ios.main");</script>');
``` 
I quickly tested this. In figwheel-bridge.js I tried to require `env.${platform}.main` instead of `figwheel.connect.build_${platform}` and it works (see #144). This would eliminate the double initialization problem.

Though, I have no opinion on which way of setting-up figwheel is better/simpler, but @jeaye is right about why `watch-and-reload` config is needed:
   1. to setup custom reload logic (specific to reagent/om-next/rum)
   2. to setup server hostname (when using real device or android simulators)
Currently command `re-natal use-figwheel` fully regenerates the env.${platform}.main namespace with correct hostname. Full regeneration is possible because this namespace should not contain any application-specific code. It contains only app-reload code. Regenerating this namespace also makes it possible to provide fixes/changes in figwheel/reload machinery without requiring any manual upgrade steps (like manual changes in project.clj) for the users.

**Comment by bhauman** [comment]
Yeah, so its way easier to regen this namespace than to have configuration in the project.clj.

That is a very good reason to just load the "main" namespace and not the figwheel build script. It also makes more things explicit instead of implicit and keeps all the setup/connection code in the one namespace.

I would say let's just load the `main` namespace instead of the figwheel build script, I'm sure this will eliminate confusing situations where you comment out the watch-and-reload call and then get some strange undefined behavior.

Also if we could move to `figwheel.client/start` instead of watch and reload that would be great.

**Comment by drapanjanas** [comment]
Alright, will just load `main` namespace then. 
Actually, I was wrong stating that namespace wich configures figwheel is always regenerated. It is regenerated only in case of `re-natal upgrade` command to propagate any updates in reloader code. 
By moving to `figwheel.client/start`. I guess you mean similar init code to https://github.com/bhauman/lein-figwheel/blob/master/example/dev/example/dev.cljs#L12? Yup, can do that.

**Comment by bhauman** [comment]
Perfect! Thanks!
