### ISSUE TITLE
Changing env.${platform}.main

### ISSUE THREAD

**Issue by jeaye** [drapanjanas/re-natal#145]
You mentioned in this comment: https://github.com/drapanjanas/re-natal/issues/143#issuecomment-334079239

> Currently command re-natal use-figwheel fully regenerates the env.${platform}.main namespace with correct hostname. Full regeneration is possible because this namespace should not contain any application-specific code. It contains only app-reload code. Regenerating this namespace also makes it possible to provide fixes/changes in figwheel/reload machinery without requiring any manual upgrade steps (like manual changes in project.clj) for the users.

This raised a red flag for me, since we have actually modified those namespaces and haven't seen any trouble. For example, my current `env/dev/env/android/main.cljs` is this:

```clojure
(ns ^:figwheel-no-load env.android.main
  (:require [reagent.core :as r]
            [cljs.spec.alpha :refer [check-asserts]]
            [lets-bet.client.mobile.android.core :as android.core]
            [lets-bet.client.mobile.navigation.views :refer [root]]
            [figwheel.client :as figwheel :include-macros true]
            [lets-bet.common.debug :refer [pprint]]))

(check-asserts true)
(enable-console-print!)

(def cnt (r/atom 0))
(defn reloader [] @cnt [root])
(def root-el (r/as-element [reloader]))

(figwheel/watch-and-reload
  :websocket-url "ws://localhost:3449/figwheel-ws"
  :heads-up-display false
  :jsload-callback #(swap! cnt inc))

(android.core/init!)
```

You'll note that the root element has changed, as well as some of the requires. When I do something like this:

```bash
$ re-natal use-android-device "192.168.0.12"
Using development host IP: '192.168.0.12'
Please run: re-natal use-figwheel to take effect.

$ re-natal use-figwheel
Cleaning...
index.ios.js was regenerated
index.android.js was regenerated
Host in RCTWebSocketExecutor.m was updated
Dev server host for iOS: localhost
Dev server host for Android: 192.168.0.12

$ git diff env/
diff --git a/env/dev/env/android/main.cljs b/env/dev/env/android/main.cljs
index cac2153..0ed01ca 100644
--- a/env/dev/env/android/main.cljs
+++ b/env/dev/env/android/main.cljs
@@ -14,7 +14,7 @@
 (def root-el (r/as-element [reloader]))
 
 (figwheel/watch-and-reload
-  :websocket-url "ws://localhost:3449/figwheel-ws"
+  :websocket-url "ws://192.168.0.12:3449/figwheel-ws"
   :heads-up-display false
   :jsload-callback #(swap! cnt inc))
```

As you can see by the diff, the changes were made by re-natal in-place, without causing any issue with the changes we had made. Is this safe for us to keep doing, or is it only by chance that things have been working?

**Comment by drapanjanas** [comment]
Thanks for bringing this up and sorry for raising red flags for you - I was wrong in the comment.
Command `re-natal use-figwheel` only replaces the hostname by regex: https://github.com/drapanjanas/re-natal/blob/master/re-natal.coffee#L764
Command `re-natal upgrade` - regenerates the env/* files:
https://github.com/drapanjanas/re-natal/blob/master/re-natal.coffee#L824
I wrongly thought they were always regerenared. And, I realise now that local configuration is still not fully local because of the hostname which is committed into SCM.
But, I see your point that there is a need for placing some custom code in development profile.

Thinking of introducing a separate namespace which would be required from env.${platform}.main and would be *only* responsible for reload machinery. It could then be regenerated in all cases and therefore .gitignored. 
That would result in:
  1. You can add custom code in dev profiles env.${platform}.main
  2. figwheel configuration including hostname is not committed into SCM
  3. Chanages in reloading code is seamlessly propagated into all projects with new re-natal versions

Other ideas how to solve this are welcome

**Comment by jeaye** [comment]
I think that's a great idea and it would address all of the issues. Separating the figwheel connection into a gitignored file would also simplify our workflow, since we're currently working around changes in the index whenever committing files.
