### ISSUE TITLE
Work on Android only

### ISSUE THREAD

**Issue by arichiardi** [drapanjanas/re-natal#3]
I would like to ask whether it would be possible to work on Android (no XCode installed) and Linux.

If no, which I can already see when I do `re-natal init myApp`, what could be done to contribute this feature? Is it a lot of work?

Thanks and very good job!

**Comment by drapanjanas** [comment]
The problem is a call to `getUuidForDevice 'iPhone 6'` during the `init` command, this is needed to for `re-natal launch` command to have some device pre-selected.
I am thinking to drop the `re-natal launch` command completely for now. This command is used only to start the iOS app without openning xcode. Personally I never use it because error log is only available in xcode, so I would give it away for  Linux compatibility. 

I will do it during the weekend probably, but if you have it working sooner just drop a PR

**Comment by drapanjanas** [comment]
Had some time for hacking and published v0.2.8 it should at least generate project on Linux. I have not tested all the way, please let me know if it worked out or not.

**Comment by arichiardi** [comment]
So fast! I will try in a few hours

**Comment by Roger** [comment]
Ha! just started and ran it on linux/android, now  i see it's supported only 20hs ago =), nice work!

**Comment by drapanjanas** [comment]
Thanks! Glad it works! :]

**Comment by arichiardi** [comment]
It creates the app structure but in my case it does not build it, complaining that it is missing `ANDROID_HOME`, which of course is there (checked with `echo $ANDROID_HOME`).

**Comment by gadfly361** [comment]
Just wanted to share that the android build worked on my linux machine with genymotion!  However, I had to run `react-native start`, which I don't think is included in the README.

---

Versions:

node: 4.2.0
re-natal: 0.2.10
chrome: 47.0.2526.80 (64-bit)
genymotion: 2.6.0
linux mint: 17.1

**Comment by drapanjanas** [comment]
Thanks a lot! I have put a note about running in linux and `react-native start` to readme. This might be some temporary problem in react-native CLI. According to [Linux and Windows support](https://facebook.github.io/react-native/docs/linux-windows-support.html) guide `react-native start` should be required only for Windows. Anyways, thanks again for the feedback!
