### ISSUE TITLE
Reduce logging output or maybe create logging levels?

### ISSUE THREAD

**Issue by seantempesta** [drapanjanas/re-natal#30]
Right now re-natal logs a lot of info to the console.  It's easy to get lost in the sea of cljs packages that are loaded and evaled (two separate messages per file).  Maybe removing some of the logging would help users see more signal than noise?  Here's what my console looks like after I disabled some of the info logs:

<img width="493" alt="screen shot 2016-03-20 at 2 55 04 pm" src="https://cloud.githubusercontent.com/assets/726276/13906739/0a930bca-eeac-11e5-8315-2d15c744367c.png">

Beautiful! :)

**Comment by drapanjanas** [comment]
Looks nice indeed. I will think about how to implement disable/enable extensive logging. Two lines for each js files were neded because in case of debugging in chrome the files are loaded synchronously one by one, and when not in browser - asynchronously, first queued and then evaled using `eval` function. In case of some strage problems IMO you still might want to know in what sequence your files are loaded.

**Comment by seantempesta** [comment]
Yeah, I hear ya.  Maybe a `var debug = true; if(debug) {...}` would suffice?

**Comment by drapanjanas** [comment]
Hey, I think it would! :)
