### ISSUE TITLE
Slow bootup times on Android

### ISSUE THREAD

**Issue by euwyn** [drapanjanas/re-natal#33]
Anyone experience slow bootup times on Android using this stack? Seems like a 1-2s lag before the JS part of the app kicks in.

**Comment by drapanjanas** [comment]
Are you talking about development mode or standalone bundle? Does the vanilla RN app works differently for you?

**Comment by NuclearKev** [comment]
I don't mean to revive a dead thread but I'm experiencing this problem as well. Vanilla RN only takes about a second whereas CLJS takes about 3s. I did a test with just a blank screen and some text, so I know it doesn't have to do with loading tons of npm packages. For the CLJS test, I used advanced optimization which is what gave me 3s - it was much longer for a developmental build. This doesn't seem to be an issue on iOS. 

To give you some more information: 
- I'm using version 0.59.9 of RN. 
- If I log the output, `4710  4749 D ReactNative: ReactInstanceManager.attachRootViewToInstance()` is what takes about 3s. After that it outputs `unning application "appName" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON`

My guess is that all the extra CLJS libs are taking forever to load? Any ideas? 

EDIT: I forgot to mention that if I list out the loaded modules, as explained in [this](https://facebook.github.io/react-native/docs/performance) post, I see a TON of CLJS libs along with RN stuff (and in my main app, react-navigation). I attempted to do the pre-load modules thing but that actually increased the time instead of lowering it...
